"""changed numeric to float for price

Revision ID: 9f74723cb0de
Revises: 15e40ed21a60
Create Date: 2023-02-03 17:03:59.536337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f74723cb0de'
down_revision = '15e40ed21a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###