"""redoing some cart functionality

Revision ID: 15e40ed21a60
Revises: 3723331fff58
Create Date: 2023-02-01 18:09:42.553905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e40ed21a60'
down_revision = '3723331fff58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('count', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'count')
    # ### end Alembic commands ###
