"""added primary key value to join table

Revision ID: 25501a92ec4b
Revises: d86b1aecab72
Create Date: 2023-01-27 18:06:50.627697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25501a92ec4b'
down_revision = 'd86b1aecab72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_products', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_products', 'id')
    # ### end Alembic commands ###
